language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
sudo: true
dist: precise
install: /bin/true
notifications:
  email:
    - github-awsforjava@amazon.com
script: mvn -q install
branches:
  only:
    - master
